---
  - name: Add Minio's user
    user:
      name: minio
      system: true
      shell: /sbin/nologin
      state: present

  - name: Make Minio's data dir
    file:
      path: /var/minio
      state: directory
      owner: minio
      group: minio
      mode: '0760'

  - name: Download Minio's binary
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/minio
      dest: /usr/sbin/minio
      owner: minio
      mode: '0740'

  - name: Generate Minio parameters
    shell: for i in $(seq 1 {{ host_count }}); do echo -n "http://{{ host_subnet }}.1$i{{ minio_volume }} http://{{ host_subnet }}.2$i{{ minio_volume }} "; done
    register: minio_parameters

  - debug:
      msg: '{{ minio_parameters["stdout"] }}'

  - name: Copy systemd Minio unit file
    template:
      src: minio.service.j2
      dest: /lib/systemd/system/minio-tenant-{{ item }}.service
    with_sequence: 1-{{ minio_tenants }}
     
  - name: Reload systemd units
    systemd:
      daemon_reload: yes
      name: minio-tenant-{{ item }}.service
      state: started
    with_sequence: 1-{{ minio_tenants }}
    
