---
- name: Main (Init) Playbook
  hosts: all
  gather_facts: false

- import_playbook: playbooks/init-all.yml
- import_playbook: playbooks/init-lb.yml
- import_playbook: playbooks/init-back.yml
- import_playbook: playbooks/install-minio.yml
- import_playbook: playbooks/install-nginx.yml
- import_playbook: playbooks/install-keepalived.yml
